export const FETCH_MOVIES = 'FETCH_MOVIES';
export const ADD_MOVIES = 'ADD_MOVIES';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED'; 
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';